version: "3.8"

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - database.env # configure mysql logs
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
